#ifndef INTRODUCTION_PARALLEL_COMPUTING_QUICKSORT_SEQ_H
#define INTRODUCTION_PARALLEL_COMPUTING_QUICKSORT_SEQ_H

#include "types.h"

void quicksort_seq(basetype *A, int len);
#endif //INTRODUCTION_PARALLEL_COMPUTING_QUICKSORT_SEQ_H
